/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author yanyanchen
 */
public class DoctorWorkLog extends javax.swing.JFrame {

    /**
     * Creates new form DoctorWorkLog
     */
    public DoctorWorkLog(String userName,String id,String request,String patientNumber,String date) {
        initComponents();
        lblUsername.setText(userName);
        lblPatientNumber.setText(patientNumber);
        lblPatientNumber1.setText(patientNumber);
        lblId.setText(id);
        lblRequest.setText(request);
        lblDate.setText(date);
        
        btnPrint.setEnabled(false);
    }
    
    public void validateFields(){
        String diagnose = txtDiagnose.getText();
        
//        &&!date.equals("--")&&!patientNumber.equals("--")&&!victim.equals("--")&&!location.equals("--")&&!descriiption.equals("--")
        if(!diagnose.equals("")){
            btnPrint.setEnabled(true);
        }else{
            btnPrint.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblRequest = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPatientNumber = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblPatientNumber1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDiagnose = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Doctor Work Log");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 155, 37));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setText("Hello,");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));

        lblUsername.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblUsername.setText("--");
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("Request Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        lblRequest.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblRequest.setText("--");
        getContentPane().add(lblRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setText("Date:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, -1));

        lblDate.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblDate.setText("--");
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("Patient Number:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        lblPatientNumber.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblPatientNumber.setText("--");
        getContentPane().add(lblPatientNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel11.setText("Request Log ID");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        lblId.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblId.setText("--");
        lblId.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblIdPropertyChange(evt);
            }
        });
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        btnPrint.setText("Print Work Log");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setText("Please add ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        lblPatientNumber1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblPatientNumber1.setText("--");
        getContentPane().add(lblPatientNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel9.setText("patients overall diagnose");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        txtDiagnose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiagnoseKeyReleased(evt);
            }
        });
        getContentPane().add(txtDiagnose, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblIdPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblIdPropertyChange
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_lblIdPropertyChange

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        String path = "/Users/yanyanchen/Desktop/";
        String userName=lblUsername.getText();
        String id=lblId.getText();
        String request=lblRequest.getText();
        String patientNumber=lblPatientNumber.getText();
        String date=lblDate.getText();
//        userName,id,request,patientNumber,date
        String diagnose=txtDiagnose.getText();
        
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try{
            PdfWriter.getInstance(doc, new FileOutputStream(path+""+userName+"WorkLog"+".pdf"));
            doc.open();
            Paragraph fileName=new Paragraph("                                                 Disease Control System");
            doc.add(fileName);
            Paragraph stringLine=new Paragraph("*********************************************************************************************************************");
            doc.add(stringLine);
            Paragraph paragraph = new Paragraph("\tRequest ID: "+id+"\nDate: "+date);
            doc.add(paragraph);
            Paragraph paragraph1 = new Paragraph("\nRequest Name: "+request+"\tDoctor Name:"+userName);
            doc.add(paragraph1);
            Paragraph paragraph2 = new Paragraph("\tPatient Number: "+patientNumber+"\nDiagnose: "+diagnose);
            doc.add(paragraph2);
            doc.add(stringLine);
            Paragraph thankMsg = new Paragraph("Thank you for your hard work!");
            doc.add(thankMsg);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DoctorWorkLog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(DoctorWorkLog.class.getName()).log(Level.SEVERE, null, ex);
        }
        doc.close();
        setVisible(false);
        
        new DoctorWorkArea(userName).setVisible(true);
//        new DoctorWorkLog(userName,id,request,String patientNumber,String date).setVisible(true);
    }//GEN-LAST:event_btnPrintActionPerformed

    private void txtDiagnoseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiagnoseKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtDiagnoseKeyReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DoctorWorkLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DoctorWorkLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DoctorWorkLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DoctorWorkLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DoctorWorkLog().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPatientNumber;
    private javax.swing.JLabel lblPatientNumber1;
    private javax.swing.JLabel lblRequest;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtDiagnose;
    // End of variables declaration//GEN-END:variables
}
