/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.UserDao;
import java.awt.BorderLayout;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author yanyanchen
 */
public class ReportingModule extends javax.swing.JFrame {
    
    

    /**
     * Creates new form ReportingModule
     */
    public ReportingModule(String name) {
        initComponents();
        lblUsername.setText(name);
        showPieChart();
    }
    
    
    
    public void showPieChart(){
        
        double a = 24.5;
        double b = 48.7;
        double c = 11.4;
        double d = 5.4;
        double e = 1.4;
        double f = 8.6;
        
        String cityName="Boston";
        
        int count = 11;
        
//        int ratioHospital=UserDao.countUserFromHospital()/UserDao.countUser();
//        int ratioCommunity=UserDao.countUserFromCommunity()/UserDao.countUser();
//        int ratioPolice=UserDao.countUserFromPolice()/UserDao.countUser();
//        int ratioHotel=UserDao.countUserFromHotel()/UserDao.countUser();
//        int ratioVaccinateUnit=UserDao.countUserFromVaccinateUnit()/UserDao.countUser();
//        int ratioCarCompany=UserDao.countUserFromCarCompany()/UserDao.countUser();
        
        
        //create dataset
      DefaultPieDataset barDataset = new DefaultPieDataset( );
      
      
//      barDataset.setValue( "Hospital" , new Double( ratioHospital ) );  
//      barDataset.setValue( "Vaccinate Unit" , new Double( ratioVaccinateUnit ) );   
//      barDataset.setValue( "Police" , new Double( ratioPolice ) );    
//      barDataset.setValue( "Community" , new Double( ratioCommunity ) );
//      barDataset.setValue( "Car Company" , new Double( ratioCarCompany ) );
//      barDataset.setValue( "Hotel" , new Double( ratioHotel ) );

        barDataset.setValue( "Hospital" , new Double( a ) );  
        barDataset.setValue( "Vaccinate Unit" , new Double( b ) );   
        barDataset.setValue( "Police" , new Double( c ) );    
        barDataset.setValue( "Community" , new Double( d ) );
        barDataset.setValue( "Car Company" , new Double( e ) );
        barDataset.setValue( "Hotel" , new Double( f ) );
      
      //create chart
       JFreeChart piechart = ChartFactory.createPieChart("Role Type Proportion Of Users",barDataset, false,true,false);//explain
      
        PiePlot piePlot =(PiePlot) piechart.getPlot();
      
       //changing pie chart blocks colors
        piePlot.setSectionPaint("Hospital", new Color(255,255,102));
        piePlot.setSectionPaint("Vaccinate Unit", new Color(102,255,102));
        piePlot.setSectionPaint("Police", new Color(255,102,153));
        piePlot.setSectionPaint("Community", new Color(120,204,204));
        piePlot.setSectionPaint("Car Company", new Color(70,204,204));
        piePlot.setSectionPaint("Hotel", new Color(0,204,204));
      
       
        piePlot.setBackgroundPaint(Color.white);
        
        //create chartPanel to display chart(graph)
        ChartPanel barChartPanel = new ChartPanel(piechart);
        panelBarChart.removeAll();
        panelBarChart.add(barChartPanel, BorderLayout.CENTER);
        panelBarChart.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarChart = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBarChart.setBackground(new java.awt.Color(153, 255, 102));
        panelBarChart.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelBarChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 650, 430));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1139, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setText("Hello,");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, -1, -1));

        lblUsername.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblUsername.setText("--");
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = lblUsername.getText();
        this.dispose();
        SystemAdminPage in=new SystemAdminPage(name);
        in.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ReportingModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ReportingModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ReportingModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ReportingModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ReportingModule().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel panelBarChart;
    // End of variables declaration//GEN-END:variables
}
